### ISSUE TITLE
char_character_full sticker issues

### ISSUE THREAD

**Issue by Landsurfer2000** [spelunky-fyi/Playlunky#6] opened 2021-03-09 19:45 UTC
when loading a char_character_full via playlunky, everything works as expected, however, autogenerated stickers for other characters no longer work, making me a tad bit confused as to which characters i have installed or not. Thanks for all of your amazing work!

**Comment by Malacath-92** [comment] 2021-03-09 22:26
Thanks for bringing it up. If you check the changeling tho you'll see that the issue is already addressed in an unreleased patch. Just give it a week or two and I'll ship that  :)

**Comment by Malacath-92** [comment] 2021-03-10 20:32
@Landsurfer2000 I decided to release a new version now because I don't see a reason to sit on a bunch of bug fixes while working on something else. So try [v0.6.0](https://github.com/spelunky-fyi/Playlunky/releases/tag/v0.6.0) and let me know how it works for you.

**Closed by Malacath-92** 2021-03-10 20:32 UTC
Labels: bug
